window.DRZIX_DATA = {
  recent: ["Paracetamol", "Amoxicillin", "Ceftriaxone", "Ondansetron"],
  drugs: [
    {
      id: "paracetamol",
      name: "Paracetamol",
      aliases: ["PCM", "Crocin", "Calpol", "Dolo"],
      category: "Fever / Pain",
      indications: ["Fever", "Pain", "Post-vaccination fever"],
      route: "PO",
      age: {
        minMonths: 2,
        note: "Suitable from 2 months onward in this starter database.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 15,
        maxSingleMg: 1000,
        maxDailyMgPerKg: 75,
        frequency: "Every 6 hours",
        duration: "3 to 5 days",
      },
      strengths: [
        { label: "125 mg/5 mL", concentrationMg: 125, concentrationMl: 5, form: "Syrup" },
        { label: "250 mg/5 mL", concentrationMg: 250, concentrationMl: 5, form: "Syrup" },
      ],
      warnings: ["Do not exceed 5 doses in 24 hours."],
      alternatives: ["Ibuprofen"],
      status: "Verified",
    },
    {
      id: "amoxicillin",
      name: "Amoxicillin",
      aliases: ["Amoxil"],
      category: "Antibiotic",
      indications: ["Otitis media", "Pneumonia", "Pharyngitis"],
      route: "PO",
      age: {
        minMonths: 1,
        note: "Use only when clinically indicated and with age-appropriate dosing.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 45,
        maxSingleMg: 1000,
        maxDailyMgPerKg: 90,
        frequency: "Twice daily",
        duration: "5 to 7 days",
      },
      strengths: [
        { label: "125 mg/5 mL", concentrationMg: 125, concentrationMl: 5, form: "Syrup" },
        { label: "250 mg/5 mL", concentrationMg: 250, concentrationMl: 5, form: "Syrup" },
        { label: "500 mg capsule", concentrationMg: 500, concentrationMl: 1, form: "Capsule" },
      ],
      warnings: ["Check for penicillin allergy before use."],
      alternatives: ["Cefixime", "Ceftriaxone"],
      status: "Verified",
    },
    {
      id: "ibuprofen",
      name: "Ibuprofen",
      aliases: ["Brufen"],
      category: "Fever / Pain",
      indications: ["Fever", "Pain", "Inflammation"],
      route: "PO",
      age: {
        minMonths: 6,
        note: "Avoid under 6 months in this starter database.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 10,
        maxSingleMg: 400,
        maxDailyMgPerKg: 40,
        frequency: "Every 8 hours",
        duration: "2 to 3 days",
      },
      strengths: [
        { label: "100 mg/5 mL", concentrationMg: 100, concentrationMl: 5, form: "Syrup" },
        { label: "200 mg tablet", concentrationMg: 200, concentrationMl: 1, form: "Tablet" },
      ],
      warnings: ["Use caution in dehydration."],
      alternatives: ["Paracetamol"],
      status: "Verified",
    },
    {
      id: "ondansetron",
      name: "Ondansetron",
      aliases: [],
      category: "Vomiting",
      indications: ["Vomiting", "Gastroenteritis"],
      route: "PO",
      age: {
        minMonths: 6,
        note: "Use for selected pediatric vomiting scenarios only.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 0.15,
        maxSingleMg: 8,
        maxDailyMgPerKg: 0.3,
        frequency: "Single dose or as directed",
        duration: "Single dose",
      },
      strengths: [
        { label: "2 mg/5 mL", concentrationMg: 2, concentrationMl: 5, form: "Syrup" },
        { label: "4 mg tablet", concentrationMg: 4, concentrationMl: 1, form: "Tablet" },
      ],
      warnings: ["Review dehydration severity before prescribing."],
      alternatives: ["Oral rehydration solution"],
      status: "Verified",
    },
    {
      id: "ceftriaxone",
      name: "Ceftriaxone",
      aliases: [],
      category: "Injection antibiotic",
      indications: ["Pneumonia", "Sepsis", "Meningitis"],
      route: "IV/IM",
      age: {
        minMonths: 1,
        note: "Use with neonatal caution and local protocols.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 50,
        maxSingleMg: 2000,
        maxDailyMgPerKg: 100,
        frequency: "Once daily",
        duration: "As clinically required",
      },
      strengths: [
        { label: "250 mg vial", concentrationMg: 250, concentrationMl: 1, form: "Vial" },
        { label: "500 mg vial", concentrationMg: 500, concentrationMl: 1, form: "Vial" },
        { label: "1 g vial", concentrationMg: 1000, concentrationMl: 1, form: "Vial" },
      ],
      warnings: ["Neonatal use requires strict protocol review."],
      alternatives: ["Cefotaxime"],
      status: "Needs review",
    },
  ],
  whoWeight: [
    { months: 1, weightKg: 4.2 },
    { months: 6, weightKg: 7.5 },
    { months: 12, weightKg: 9.5 },
    { months: 24, weightKg: 12.0 },
    { months: 36, weightKg: 14.2 },
    { months: 48, weightKg: 16.2 },
    { months: 60, weightKg: 18.2 },
  ],
};
