window.DRZIX_DATA = {
  recent: ["Paracetamol", "Amoxicillin", "Ceftriaxone", "Ondansetron", "Cetirizine", "Dexamethasone"],
  drugs: [
    {
      id: "paracetamol",
      name: "Paracetamol",
      aliases: ["PCM", "Crocin", "Calpol", "Dolo"],
      category: "Fever / Pain",
      indications: ["Fever", "Pain", "Post-vaccination fever"],
      route: "PO",
      age: {
        minMonths: 2,
        note: "Suitable from 2 months onward in this starter database.",
        alternativesByAge: [
          { maxMonths: 1, name: "Clinical review", note: "Newborn fever or pain needs specialist review." },
        ],
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 15,
        maxSingleMg: 1000,
        maxDailyMgPerKg: 75,
        frequency: "Every 6 hours",
        duration: "3 to 5 days",
      },
      strengths: [
        { label: "125 mg/5 mL", concentrationMg: 125, concentrationMl: 5, form: "Syrup" },
        { label: "250 mg/5 mL", concentrationMg: 250, concentrationMl: 5, form: "Syrup" },
      ],
      warnings: ["Do not exceed 5 doses in 24 hours."],
      alternatives: ["Ibuprofen"],
      status: "Verified",
    },
    {
      id: "amoxicillin",
      name: "Amoxicillin",
      aliases: ["Amoxil"],
      category: "Antibiotic",
      indications: ["Otitis media", "Pneumonia", "Pharyngitis"],
      route: "PO",
      age: {
        minMonths: 1,
        note: "Use only when clinically indicated and with age-appropriate dosing.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 45,
        maxSingleMg: 1000,
        maxDailyMgPerKg: 90,
        frequency: "Twice daily",
        duration: "5 to 7 days",
      },
      strengths: [
        { label: "125 mg/5 mL", concentrationMg: 125, concentrationMl: 5, form: "Syrup" },
        { label: "250 mg/5 mL", concentrationMg: 250, concentrationMl: 5, form: "Syrup" },
        { label: "500 mg capsule", concentrationMg: 500, concentrationMl: 1, form: "Capsule" },
      ],
      warnings: ["Check for penicillin allergy before use."],
      alternatives: ["Cefixime", "Ceftriaxone"],
      status: "Verified",
    },
    {
      id: "ibuprofen",
      name: "Ibuprofen",
      aliases: ["Brufen"],
      category: "Fever / Pain",
      indications: ["Fever", "Pain", "Inflammation"],
      route: "PO",
      age: {
        minMonths: 6,
        note: "Avoid under 6 months in this starter database.",
        alternativesByAge: [
          { maxMonths: 5, name: "Paracetamol", note: "Use paracetamol instead of ibuprofen below 6 months." },
        ],
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 10,
        maxSingleMg: 400,
        maxDailyMgPerKg: 40,
        frequency: "Every 8 hours",
        duration: "2 to 3 days",
      },
      strengths: [
        { label: "100 mg/5 mL", concentrationMg: 100, concentrationMl: 5, form: "Syrup" },
        { label: "200 mg tablet", concentrationMg: 200, concentrationMl: 1, form: "Tablet" },
      ],
      warnings: ["Use caution in dehydration."],
      alternatives: ["Paracetamol"],
      status: "Verified",
    },
    {
      id: "ondansetron",
      name: "Ondansetron",
      aliases: [],
      category: "Vomiting",
      indications: ["Vomiting", "Gastroenteritis"],
      route: "PO",
      age: {
        minMonths: 6,
        note: "Use for selected pediatric vomiting scenarios only.",
        alternativesByAge: [
          { maxMonths: 5, name: "Oral rehydration solution", note: "Below 6 months, start with ORS and clinical review." },
        ],
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 0.15,
        maxSingleMg: 8,
        maxDailyMgPerKg: 0.3,
        frequency: "Single dose or as directed",
        duration: "Single dose",
      },
      strengths: [
        { label: "2 mg/5 mL", concentrationMg: 2, concentrationMl: 5, form: "Syrup" },
        { label: "4 mg tablet", concentrationMg: 4, concentrationMl: 1, form: "Tablet" },
      ],
      warnings: ["Review dehydration severity before prescribing."],
      alternatives: ["Oral rehydration solution"],
      status: "Verified",
    },
    {
      id: "ceftriaxone",
      name: "Ceftriaxone",
      aliases: [],
      category: "Injection antibiotic",
      indications: ["Pneumonia", "Sepsis", "Meningitis"],
      route: "IV/IM",
      age: {
        minMonths: 1,
        note: "Use with neonatal caution and local protocols.",
        alternativesByAge: [
          { maxMonths: 0, name: "Cefotaxime", note: "Neonatal review and local protocol are required." },
        ],
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 50,
        maxSingleMg: 2000,
        maxDailyMgPerKg: 100,
        frequency: "Once daily",
        duration: "As clinically required",
      },
      strengths: [
        { label: "250 mg vial", concentrationMg: 250, concentrationMl: 1, form: "Vial" },
        { label: "500 mg vial", concentrationMg: 500, concentrationMl: 1, form: "Vial" },
        { label: "1 g vial", concentrationMg: 1000, concentrationMl: 1, form: "Vial" },
      ],
      warnings: ["Neonatal use requires strict protocol review."],
      alternatives: ["Cefotaxime"],
      status: "Needs review",
    },
    {
      id: "cetirizine",
      name: "Cetirizine",
      aliases: [],
      category: "Allergy",
      indications: ["Allergic rhinitis", "Urticaria", "Itching"],
      route: "PO",
      age: {
        minMonths: 12,
        note: "Use age-band dosing for young children.",
        alternativesByAge: [
          { maxMonths: 11, name: "Clinical review", note: "Cetirizine liquid is prescribed from 1 year; younger infants need clinician review." },
        ],
      },
      dose: {
        type: "ageBand",
        bands: [
          { minMonths: 12, maxMonths: 23, label: "12 to 23 months", amountMg: 2.5, frequency: "Once daily", duration: "As needed" },
          { minMonths: 24, maxMonths: 59, label: "2 to 5 years", amountMg: 2.5, frequency: "Twice daily", duration: "As needed" },
          { minMonths: 60, maxMonths: 143, label: "6 to 11 years", amountMg: 5, frequency: "Twice daily", duration: "As needed" },
          { minMonths: 144, maxMonths: null, label: "12 years and above", amountMg: 10, frequency: "Once daily", duration: "As needed" },
        ],
        frequency: "Age dependent",
        duration: "As needed",
      },
      strengths: [
        { label: "5 mg/5 mL syrup", concentrationMg: 5, concentrationMl: 5, form: "Syrup" },
        { label: "10 mg tablet", concentrationMg: 10, concentrationMl: 1, form: "Tablet" },
      ],
      warnings: ["Age-band dosing only. Check sleepiness and local protocol."],
      alternatives: ["Loratadine"],
      status: "Verified",
    },
    {
      id: "zinc",
      name: "Zinc",
      aliases: [],
      category: "Diarrhea support",
      indications: ["Acute diarrhea"],
      route: "PO",
      age: {
        minMonths: 0,
        note: "Age-band dosing for diarrhea support in children.",
      },
      dose: {
        type: "ageBand",
        bands: [
          { minMonths: 0, maxMonths: 5, label: "Under 6 months", amountMg: 10, frequency: "Once daily", duration: "10 to 14 days" },
          { minMonths: 6, maxMonths: null, label: "6 months and above", amountMg: 20, frequency: "Once daily", duration: "10 to 14 days" },
        ],
        frequency: "Once daily",
        duration: "10 to 14 days",
      },
      strengths: [
        { label: "10 mg syrup", concentrationMg: 10, concentrationMl: 5, form: "Syrup" },
        { label: "20 mg tablet", concentrationMg: 20, concentrationMl: 1, form: "Tablet" },
      ],
      warnings: ["Used with oral rehydration and continued feeding."],
      alternatives: ["ORS"],
      status: "Verified",
    },
    {
      id: "amikacin",
      name: "Amikacin",
      aliases: [],
      category: "Injection antibiotic",
      indications: ["Sepsis", "Serious gram-negative infection"],
      route: "IV/IM",
      age: {
        minMonths: 1,
        note: "Injectable dose requires renal monitoring and local protocol review.",
        alternativesByAge: [
          { maxMonths: 0, name: "Gentamicin", note: "Use protocol-based neonatal aminoglycoside choice." },
        ],
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 15,
        maxSingleMg: 1500,
        maxDailyMgPerKg: 15,
        frequency: "Once daily",
        duration: "As clinically required",
      },
      strengths: [
        { label: "100 mg/2 mL vial", concentrationMg: 100, concentrationMl: 2, form: "Vial" },
        { label: "500 mg/2 mL vial", concentrationMg: 500, concentrationMl: 2, form: "Vial" },
      ],
      warnings: ["Monitor renal function and hearing according to protocol."],
      alternatives: ["Gentamicin"],
      status: "Needs review",
    },
    {
      id: "salbutamol",
      name: "Salbutamol",
      aliases: ["Albuterol"],
      category: "Respiratory",
      indications: ["Wheeze", "Bronchospasm", "Asthma relief"],
      route: "Inhaled",
      age: {
        minMonths: 6,
        note: "Use age-appropriate inhaler or nebulization technique.",
        alternativesByAge: [
          { maxMonths: 5, name: "Clinical review", note: "Young infants need clinician assessment before inhaled salbutamol." },
        ],
      },
      dose: {
        type: "fixed",
        amount: 2,
        unit: "puffs",
        note: "Use 1 or 2 puffs when needed; maximum 4 times in 24 hours.",
        frequency: "Every 4 to 6 hours as needed",
        duration: "As needed",
      },
      strengths: [
        { label: "100 mcg/puff inhaler", concentrationMg: 0.1, concentrationMl: 1, form: "Inhaler" },
      ],
      warnings: ["Confirm inhaler technique and spacer use when available."],
      alternatives: ["Nebulized salbutamol"],
      status: "Verified",
    },
    {
      id: "prednisolone",
      name: "Prednisolone",
      aliases: [],
      category: "Steroid",
      indications: ["Croup", "Sore throat", "Inflammatory conditions"],
      route: "PO",
      age: {
        minMonths: 0,
        note: "Use indication-specific pediatric dosing and tapering only when needed.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 1,
        maxSingleMg: 50,
        maxDailyMgPerKg: 1,
        frequency: "Single dose or as directed",
        duration: "Single dose or short course",
      },
      strengths: [
        { label: "1 mg/mL liquid", concentrationMg: 1, concentrationMl: 1, form: "Liquid" },
        { label: "10 mg/mL liquid", concentrationMg: 10, concentrationMl: 1, form: "Liquid" },
        { label: "5 mg tablet", concentrationMg: 5, concentrationMl: 1, form: "Tablet" },
      ],
      warnings: ["Follow local tapering guidance if a longer course is prescribed."],
      alternatives: ["Dexamethasone"],
      status: "Verified",
    },
    {
      id: "dexamethasone",
      name: "Dexamethasone",
      aliases: [],
      category: "Steroid",
      indications: ["Croup", "Severe sore throat", "Wheeze"],
      route: "PO/IV/IM",
      age: {
        minMonths: 0,
        note: "Use indication-specific pediatric dosing and follow local airway guidance.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 0.15,
        maxSingleMg: 10,
        maxDailyMgPerKg: 0.15,
        frequency: "Single dose",
        duration: "Single dose",
      },
      strengths: [
        { label: "0.5 mg tablet", concentrationMg: 0.5, concentrationMl: 1, form: "Tablet" },
        { label: "4 mg tablet", concentrationMg: 4, concentrationMl: 1, form: "Tablet" },
        { label: "8 mg tablet", concentrationMg: 8, concentrationMl: 1, form: "Tablet" },
      ],
      warnings: ["Use as a single-dose steroid option for croup-type presentations when indicated."],
      alternatives: ["Prednisolone"],
      status: "Verified",
    },
    {
      id: "oral_rehydration_salts",
      name: "Oral Rehydration Salts",
      aliases: ["ORS", "Dioralyte"],
      category: "Diarrhea support",
      indications: ["Diarrhea", "Dehydration"],
      route: "PO",
      age: {
        minMonths: 0,
        note: "Use with small frequent sips and local packet directions.",
      },
      dose: {
        type: "fixed",
        amount: 1,
        unit: "packet",
        note: "Prepare according to the packet and give frequent small sips.",
        frequency: "Throughout the day",
        duration: "As needed",
      },
      strengths: [
        { label: "ORS sachet", concentrationMg: 1, concentrationMl: 1, form: "Sachet" },
      ],
      warnings: ["Continue feeding and seek care if the child cannot drink or is getting worse."],
      alternatives: ["Continue feeding"],
      status: "Verified",
    },
  ],
  emergencies: [
    {
      id: "anaphylaxis",
      name: "Anaphylaxis",
      category: "Emergency",
      indications: ["Airway swelling", "Wheeze", "Hypotension", "Allergic collapse"],
      age: {
        minMonths: 0,
        note: "Lay child flat or sitting with legs extended; do not allow standing.",
      },
      primaryDrugId: "adrenaline",
      steps: [
        "Remove the trigger if possible and call for help.",
        "Give IM adrenaline promptly.",
        "Position the child flat or sitting with legs extended.",
        "Repeat adrenaline after 5 minutes if not improving.",
      ],
      note: "Antihistamines and corticosteroids do not treat anaphylaxis itself.",
      status: "Emergency",
    },
    {
      id: "seizure",
      name: "Prolonged seizure",
      category: "Emergency",
      indications: ["Seizure over 5 minutes", "Unknown seizure duration"],
      age: {
        minMonths: 0,
        note: "Treat if total seizure duration is 5 minutes or more, or unknown.",
      },
      primaryDrugId: "midazolam",
      steps: [
        "Protect the airway and keep the child safe.",
        "Give first-line benzodiazepine if seizure continues.",
        "Do not exceed 2 appropriate benzodiazepine doses including pre-hospital doses.",
        "Escalate to second-line treatment if still seizing.",
      ],
      note: "Midazolam may be given buccal, intranasal, IV, IM, or IO depending on local protocol.",
      status: "Emergency",
    },
    {
      id: "hypoglycaemia",
      name: "Hypoglycaemia",
      category: "Emergency",
      indications: ["Low blood sugar", "Lethargy", "Seizure with low BGL"],
      age: {
        minMonths: 0,
        note: "Enteral glucose is preferred if the child is conscious and safe to swallow.",
      },
      primaryDrugId: "glucose_10_percent",
      steps: [
        "Check the blood glucose level immediately.",
        "Use enteral glucose if conscious and able to swallow safely.",
        "Give IV 10% glucose if severe or unable to take orally.",
        "Recheck glucose and continue monitoring after correction.",
      ],
      note: "A rapid IV correction is needed when the child cannot take oral carbohydrate.",
      status: "Emergency",
    },
    {
      id: "shock",
      name: "Shock / hypovolaemia",
      category: "Emergency",
      indications: ["Poor perfusion", "Tachycardia", "Hypotension", "Delayed capillary refill"],
      age: {
        minMonths: 0,
        note: "Use isotonic bolus and reassess frequently.",
      },
      primaryDrugId: "isotonic_bolus",
      steps: [
        "Give an isotonic crystalloid bolus.",
        "Reassess the child after each bolus.",
        "Titrate subsequent boluses to response.",
        "Escalate early if shock persists.",
      ],
      note: "Volume needs vary; start with 10 to 20 mL/kg depending on the situation and local protocol.",
      status: "Emergency",
    },
  ],
  emergencyDrugs: [
    {
      id: "adrenaline",
      name: "Adrenaline",
      aliases: ["Epinephrine"],
      category: "Emergency",
      indications: ["Anaphylaxis", "Cardiac arrest", "Severe allergic collapse"],
      route: "IM",
      age: {
        minMonths: 0,
        note: "IM adrenaline is the first-line treatment for anaphylaxis.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 0.01,
        maxSingleMg: 0.5,
        maxDailyMgPerKg: 0.01,
        frequency: "Repeat after 5 minutes if needed",
        duration: "Immediate",
      },
      strengths: [
        { label: "1:1000 ampoule", concentrationMg: 1, concentrationMl: 1, form: "Ampoule" },
        { label: "Autoinjector 150 mcg", concentrationMg: 0.15, concentrationMl: 1, form: "Device" },
        { label: "Autoinjector 300 mcg", concentrationMg: 0.3, concentrationMl: 1, form: "Device" },
      ],
      warnings: ["Use 0.01 mL/kg of 1:1000 IM for anaphylaxis; do not allow the child to stand after dosing."],
      alternatives: ["Emergency review"],
      status: "Emergency",
    },
    {
      id: "midazolam",
      name: "Midazolam",
      aliases: [],
      category: "Emergency anticonvulsant",
      indications: ["Prolonged seizure", "Status epilepticus"],
      route: "IV/IM/Buccal/IN",
      age: {
        minMonths: 0,
        note: "Use a protocol-based emergency seizure rescue dose.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 0.15,
        maxSingleMg: 10,
        maxDailyMgPerKg: 0.3,
        frequency: "Single rescue dose",
        duration: "Immediate",
      },
      strengths: [
        { label: "5 mg/mL ampoule", concentrationMg: 5, concentrationMl: 1, form: "Ampoule" },
      ],
      warnings: ["Buccal or intranasal rescue dosing is protocol-based; monitor breathing closely."],
      alternatives: ["Diazepam"],
      status: "Emergency",
    },
    {
      id: "diazepam",
      name: "Diazepam",
      aliases: [],
      category: "Emergency anticonvulsant",
      indications: ["Prolonged seizure", "Status epilepticus"],
      route: "IV/IO",
      age: {
        minMonths: 0,
        note: "IV diazepam is a seizure rescue option when available and appropriate.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 0.3,
        maxSingleMg: 10,
        maxDailyMgPerKg: 0.3,
        frequency: "Single rescue dose",
        duration: "Immediate",
      },
      strengths: [
        { label: "5 mg/mL ampoule", concentrationMg: 5, concentrationMl: 1, form: "Ampoule" },
      ],
      warnings: ["Do not use IM diazepam in this starter database."],
      alternatives: ["Midazolam"],
      status: "Emergency",
    },
    {
      id: "glucose_10_percent",
      name: "10% Glucose",
      aliases: ["Dextrose 10%"],
      category: "Emergency carbohydrate",
      indications: ["Hypoglycaemia"],
      route: "IV",
      age: {
        minMonths: 0,
        note: "Use IV glucose correction for severe hypoglycaemia.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 200,
        maxSingleMg: 0,
        maxDailyMgPerKg: 200,
        frequency: "Repeat if required",
        duration: "Immediate",
      },
      strengths: [
        { label: "10% glucose", concentrationMg: 10, concentrationMl: 1, form: "Fluid" },
      ],
      warnings: ["Guide output as mL/kg bolus rather than mg-based display in the emergency screen."],
      alternatives: ["Oral carbohydrate if conscious"],
      status: "Emergency",
    },
    {
      id: "isotonic_bolus",
      name: "Isotonic fluid bolus",
      aliases: ["0.9% saline bolus"],
      category: "Emergency fluid",
      indications: ["Shock", "Hypovolaemia", "Severe dehydration"],
      route: "IV",
      age: {
        minMonths: 0,
        note: "Use 10 to 20 mL/kg isotonic fluid and reassess.",
      },
      dose: {
        type: "perKg",
        amountMgPerKg: 20,
        maxSingleMg: 0,
        maxDailyMgPerKg: 20,
        frequency: "Repeat after reassessment",
        duration: "Immediate",
      },
      strengths: [
        { label: "0.9% saline", concentrationMg: 1, concentrationMl: 1, form: "Fluid" },
      ],
      warnings: ["Emergency fluid bolus output is shown in mL/kg rather than medicine mg."],
      alternatives: ["Balanced crystalloid"],
      status: "Emergency",
    },
  ],
  whoWeight: [
    { months: 1, weightKg: 4.2 },
    { months: 6, weightKg: 7.5 },
    { months: 12, weightKg: 9.5 },
    { months: 24, weightKg: 12.0 },
    { months: 36, weightKg: 14.2 },
    { months: 48, weightKg: 16.2 },
    { months: 60, weightKg: 18.2 },
  ],
};
